### ISSUE TITLE
More than one account?

### ISSUE THREAD

**Issue by sephentos** [bfren/docker-ftps#79]
Hello,

is it possible to create more than one FTP account? According to the ENV it seems that only one user is possible. 
Would it possibly be possible to implement this feature otherwise?

**Comment by bfren** [comment]
I have looked at this before, but it causes some issues with permissions on the local filesystem (i.e. the volume that's mounted).

One way to do it is by having multiple containers set up - one for each user - and using port forwarding from the host to separate them.
